// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD97ZeFiIlMgYU4_1UooJcYA6KhIfatQc',
    appId: '1:1023430264697:web:7a5ae54f0ebbad87d391a8',
    messagingSenderId: '1023430264697',
    projectId: 'custom-label-bottle-crm',
    authDomain: 'custom-label-bottle-crm.firebaseapp.com',
    storageBucket: 'custom-label-bottle-crm.firebasestorage.app',
    measurementId: 'G-MQ75JJ8HJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD6MOT72n266hchSRcFwjv4mKdUf1eDcs',
    appId: '1:1023430264697:android:aab393fface31ee2d391a8',
    messagingSenderId: '1023430264697',
    projectId: 'custom-label-bottle-crm',
    storageBucket: 'custom-label-bottle-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuav6cYuqu59eQfFDIwFLq1l1JUXBxiKE',
    appId: '1:1023430264697:ios:c5f383c2288c563ed391a8',
    messagingSenderId: '1023430264697',
    projectId: 'custom-label-bottle-crm',
    storageBucket: 'custom-label-bottle-crm.firebasestorage.app',
    iosBundleId: 'com.example.clwbCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuav6cYuqu59eQfFDIwFLq1l1JUXBxiKE',
    appId: '1:1023430264697:ios:c5f383c2288c563ed391a8',
    messagingSenderId: '1023430264697',
    projectId: 'custom-label-bottle-crm',
    storageBucket: 'custom-label-bottle-crm.firebasestorage.app',
    iosBundleId: 'com.example.clwbCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD97ZeFiIlMgYU4_1UooJcYA6KhIfatQc',
    appId: '1:1023430264697:web:5a98d28220ce0732d391a8',
    messagingSenderId: '1023430264697',
    projectId: 'custom-label-bottle-crm',
    authDomain: 'custom-label-bottle-crm.firebaseapp.com',
    storageBucket: 'custom-label-bottle-crm.firebasestorage.app',
    measurementId: 'G-M40CP89M1D',
  );
}
