import 'package:clwb_crm/screens/orders/models/order_model.dart';


class OrdersDummyData {
  static List<OrderModel> list = [
    OrderModel(
      id: '1',
      clientId: 'c1',
      clientNameSnapshot: 'Cafe Snowtrail',
      orderNumber: '#ORD-102',
      itemId: 'i1',
      itemNameSnapshot: '500ml Bottle',
      bottleSize: '500ml',
      packSize: 24,
      orderedQuantity: 100,
      producedQuantity: 20,
      deliveredQuantity: 0,
      remainingQuantity: 80,
      ratePerBottle: 8,
      totalAmount: 800,
      paidAmount: 200,
      dueAmount: 600,
      orderStatus: 'in_production',
      productionStatus: 'in_progress',
      deliveryStatus: 'pending',
      expectedProductionStartDate: DateTime(2026, 1, 25),
      expectedDeliveryDate: DateTime(2026, 1, 28),
      nextDeliveryDate: DateTime(2026, 1, 30),
      notes: null,
      isPriority: true,
      createdBy: 'admin',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isActive: true,
    ),
    OrderModel(
      id: '2',
      clientId: 'c2',
      clientNameSnapshot: 'Sunrise Eatery',
      orderNumber: '#ORD-101',
      itemId: 'i2',
      itemNameSnapshot: '1L Bottle',
      bottleSize: '1L',
      packSize: 12,
      orderedQuantity: 500,
      producedQuantity: 500,
      deliveredQuantity: 500,
      remainingQuantity: 0,
      ratePerBottle: 10,
      totalAmount: 5000,
      paidAmount: 5000,
      dueAmount: 0,
      orderStatus: 'completed',
      productionStatus: 'completed',
      deliveryStatus: 'completed',
      expectedProductionStartDate: DateTime(2026, 1, 20),
      expectedDeliveryDate: DateTime(2026, 1, 27),
      nextDeliveryDate: null,
      notes: null,
      isPriority: true,
      createdBy: 'admin',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isActive: true,
    ),
    OrderModel(
      id: '22',
      clientId: 'c22',
      clientNameSnapshot: 'Sunrise Eatery',
      orderNumber: '#ORD-1012',
      itemId: 'i22',
      itemNameSnapshot: '1L Bottle',
      bottleSize: '1L',
      packSize: 12,
      orderedQuantity: 500,
      producedQuantity: 500,
      deliveredQuantity: 500,
      remainingQuantity: 0,
      ratePerBottle: 10,
      totalAmount: 5000,
      paidAmount: 5000,
      dueAmount: 0,
      orderStatus: 'completed',
      productionStatus: 'completed',
      deliveryStatus: 'completed',
      expectedProductionStartDate: DateTime(2026, 1, 20),
      expectedDeliveryDate: DateTime(2026, 1, 27),
      nextDeliveryDate: null,
      notes: null,
      isPriority: true,
      createdBy: 'admin',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isActive: true,
    ),
    OrderModel(
      id: '3',
      clientId: 'c3',
      clientNameSnapshot: 'Snowpeak Resorts',
      orderNumber: '#ORD-100',
      itemId: 'i3',
      itemNameSnapshot: '500ml Bottle',
      bottleSize: '500ml',
      packSize: 24,
      orderedQuantity: 60,
      producedQuantity: 60,
      deliveredQuantity: 60,
      remainingQuantity: 0,
      ratePerBottle: 9,
      totalAmount: 540,
      paidAmount: 540,
      dueAmount: 0,
      orderStatus: 'completed',
      productionStatus: 'completed',
      deliveryStatus: 'completed',
      expectedProductionStartDate: DateTime(2026, 1, 24),
      expectedDeliveryDate: DateTime(2026, 1, 27),
      nextDeliveryDate: null,
      notes: null,
      isPriority: false,
      createdBy: 'admin',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isActive: true,
    ),
    OrderModel(
      id: '4',
      clientId: 'c4',
      clientNameSnapshot: 'SnowPeak Resorts',
      orderNumber: '#ORD-1000',
      itemId: 'i4',
      itemNameSnapshot: '500ml Bottle',
      bottleSize: '500ml',
      packSize: 24,
      orderedQuantity: 60,
      producedQuantity: 60,
      deliveredQuantity: 60,
      remainingQuantity: 0,
      ratePerBottle: 9,
      totalAmount: 540,
      paidAmount: 540,
      dueAmount: 0,
      orderStatus: 'completed',
      productionStatus: 'completed',
      deliveryStatus: 'completed',
      expectedProductionStartDate: DateTime(2026, 1, 24),
      expectedDeliveryDate: DateTime(2026, 1, 27),
      nextDeliveryDate: null,
      notes: null,
      isPriority: false,
      createdBy: 'admin',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isActive: true,
    ),
    OrderModel(
      id: '44',
      clientId: 'c44',
      clientNameSnapshot: 'SnowPeak Resorts',
      orderNumber: '#ORD-10004',
      itemId: 'i44',
      itemNameSnapshot: '500ml Bottle',
      bottleSize: '500ml',
      packSize: 24,
      orderedQuantity: 60,
      producedQuantity: 60,
      deliveredQuantity: 60,
      remainingQuantity: 0,
      ratePerBottle: 9,
      totalAmount: 540,
      paidAmount: 540,
      dueAmount: 0,
      orderStatus: 'completed',
      productionStatus: 'completed',
      deliveryStatus: 'completed',
      expectedProductionStartDate: DateTime(2026, 1, 24),
      expectedDeliveryDate: DateTime(2026, 1, 27),
      nextDeliveryDate: null,
      notes: null,
      isPriority: false,
      createdBy: 'admin',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isActive: true,
    ),
  ];
}
